source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

target 'VRMaskColoredButton_ExampleSwift', :exclusive => true do
  pod "VRMaskColoredButton", :path => "../"
end

target 'VRMaskColoredButton_ExampleObjC', :exclusive => true do
    pod "VRMaskColoredButton", :path => "../"
end

target 'VRMaskColoredButton_Tests', :exclusive => true do
  pod "VRMaskColoredButton", :path => "../"

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
end
